project: 
  type: website
  render: 
    - "!status/"
    - "*.qmd"

website:
  title: "ENIGMA trial"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: doc/status.qmd
        text: Status
      - href: doc/kilde.qmd
        text: Kilde
      - href: doc/about.qmd
        text: Om
  page-footer:
    center:
      - text: "License: GPL v3"
        href: LICENSE.html

format:
  html:
    theme: simplex

knitr:
  opts_chunk:
    echo: false

execute:
  freeze: auto
  echo: true

editor:
  markdown: 
    wrap: 72
    canonical: true
  
author:
  - name: Andreas Gammelgaard Damsbo
    orcid: 0000-0002-7559-1154
    email: andrlr@rm.dk
    url: https://pure.au.dk/portal/en/persons/andreas-gammelgaard-damsbo(e3c4afce-3eba-4456-8b8b-2fd90775c87a).html
    affiliations:
      - ref: dsc
affiliations:
  - id: dsc
    name: Danish Stroke Centre, AUH
    department: Neurology
    city: Aarhus
    country: Denmark
    url: https://www.en.auh.dk/departments/danish-stroke-centre/
