project: 
  type: website
  render: 
    - "!status/"
    - "*.qmd"

website:
  title: "ENIGMA trial"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: doc/status.qmd
        text: Status
      - href: doc/papers.qmd
        text: Udgivelser
      - href: doc/kilde.qmd
        text: Sidekilde
      - href: doc/about.qmd
        text: Om
  page-footer:
    center:
      - text: "License: GPL v3"
        href: LICENSE.html

format:
  html:
    theme: simplex

knitr:
  opts_chunk:
    echo: false

execute:
  freeze: auto
  echo: true

editor:
  markdown: 
    wrap: 72
    canonical: true
  

