---
title: "Om ENIGMA"
editor: visual
---

# ENIGMA studiet

## Baggrund

-   Formålet er at undersøge kognitiv svækkelse efter stroke
-   Til undersøgelsen indgår MR, blodprøver, spørgeskemaer og kognitiv
    undersøgelse
-   Opfølgningsstudie over 12 måneder og med registerbaseret
    langtidsopfølgning
-   Mål om 150 patienter over 3,5 år
-   RESIST-patienter kan inkluderes - langtidsopfølgning

## Kriterier

| Inklusion       | Eksklusion                         |
|-----------------|------------------------------------|
| Personer ≥60 år | mRS \> 2                           |
| AIS eller TCI   | Konkurrerende livstruende sygdom   |
| MR-verificeret  | Anden betydelig neurologisk sygdom |
|                 | Skal selv gives samtykke           |
|                 | Skal tåle MR med kontrast          |
|                 | eGFR \< 30                         |

## Ny viden

-   Småkarssygdom og kognitiv funktion
-   Fysisk aktivitet og kognitiv funktion før/efter
-   Perkonditionering og kognitivt outcome
-   Tidligere opmærksomhed på tab af kognitiv funktion
-   Mikrocirkulation ved AIS
